name: Build Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: Install packages
       uses: actions/checkout@v4
     - name: Build artifacts
       run: | 
          ls -l 
          
